# https://qiita.com/hkusu/items/39eb92dbd4d6db8a14d8

name: Review Assign

on:
  pull_request:
    types: [ opened, ready_for_review ]

env:
  REVIEWERS: "Kaito-Dogi"

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1.3.1
        with:
          assignees: ${{ github.actor }}
          reviewers: ${{ env.REVIEWERS }}
          ready-comment: "Ready for review :rocket:"
