# https://github.com/e10dokup/CiSample/blob/feature/create_lint/.github/workflows/run_lint.yml

name: Run Lint

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_lint:
    runs-on: ubuntu-latest
    env:
      JVM_OPTS: '-Xmx2048m -Xms512m'
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError -XX:MaxMetaspaceSize=1g -XX:+UseParallelGC" -Dorg.gradle.daemon=false'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Install Danger
        run: |
          gem install bundler
          bundle install
      - name: Run Lint
        run: |
          ./gradlew lintDebug --no-daemon
      - name: Copy Lint Result
        if: always()
        run: |
          mkdir -p ./lint
          find . -type f -regex ".*/build/reports/lint-.*xml" | xargs -r cp --parents --target-directory=./lint
      - name: Run Danger
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: danger --danger_id=lint
