# https://github.com/e10dokup/CiSample/blob/master/.github/workflows/run_test.yml

name: Run Test

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_test:
    runs-on: ubuntu-latest
    env:
      JVM_OPTS: '-Xmx2048m -Xms512m'
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError -XX:MaxMetaspaceSize=1g -XX:+UseParallelGC" -Dorg.gradle.daemon=false'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Install Danger
        run: |
          gem install bundler
          bundle install
      - name: Run Test
        env:
          DELETE_ACCOUNT_URL: ${{ vars.DELETE_ACCOUNT_URL }}
          HCAPTCHA_SITE_KEY_DEV: ${{ secrets.HCAPTCHA_SITE_KEY_DEV }}
          HCAPTCHA_SITE_KEY_PROD: ${{ secrets.HCAPTCHA_SITE_KEY_PROD }}
          PRIVACY_POLICY_URL: ${{ vars.PRIVACY_POLICY_URL }}
          RAKUTEN_AFFILIATE_ID_DEV: ${{ secrets.RAKUTEN_AFFILIATE_ID_DEV }}
          RAKUTEN_AFFILIATE_ID_PROD: ${{ secrets.RAKUTEN_AFFILIATE_ID_PROD }}
          RAKUTEN_APPLICATION_ID_DEV: ${{ secrets.RAKUTEN_APPLICATION_ID_DEV }}
          RAKUTEN_APPLICATION_ID_PROD: ${{ secrets.RAKUTEN_APPLICATION_ID_PROD }}
          RAKUTEN_DEVELOPERS_URL: ${{ vars.RAKUTEN_DEVELOPERS_URL }}
          SUPABASE_KEY_DEV: ${{ secrets.SUPABASE_KEY_DEV }}
          SUPABASE_KEY_PROD: ${{ secrets.SUPABASE_KEY_PROD }}
          SUPABASE_URL_DEV: ${{ secrets.SUPABASE_URL_DEV }}
          SUPABASE_URL_PROD: ${{ secrets.SUPABASE_URL_PROD }}
          TERMS_OF_USE: ${{ vars.TERMS_OF_USE }}
        run: ./gradlew test --stacktrace
      - name: Copy Test Result
        if: always()
        run: |
          mkdir -p ./test-results
          find . -type f -regex ".*/test-results/.*/.*.xml" | xargs -r cp --parents --target-directory=./test-results
      - name: Run Danger
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: danger --danger_id=test
